version: '2'

networks:
  back-tier:
    driver: bridge

services:
    node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
    - 9100:9100
    expose:
    - 9100
    networks:
    - back-tier
 
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 8080:8080
    expose:
    - 8080
    networks:
    - back-tier


